# Generated by Django 4.0.4 on 2022-06-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bolano', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
